# Gunakan Node.js LTS sebagai base image
FROM node:18-alpine

# Tentukan working directory di dalam container
WORKDIR /usr/src/app

# Salin package.json dan package-lock.json ke dalam container
COPY package*.json ./

# Install dependencies
RUN npm install

# Salin seluruh file proyek ke dalam container
COPY . .

# Expose port 3000 (sesuai dengan port pada app.js)
EXPOSE 3000

# Jalankan aplikasi
CMD ["node", "app.js"]
